# Data sources


The data sets we are going to use in our analyses come from NEW YORK Open Data, a popular website with various types of official data sets published by New York City agencies. To explore the rental apartments in NYC, we need to know some basic information about buildings, such as the time the buildings start to be built and completed, statistics about different apartment types, etc. Our first data set is Housing New York Units by Building, in which multiple information related to New York apartment information from 2014/01/01 to 2020/09/30 is collected: building id, construction type and counting of apartments with different number of bedrooms and number of units in the rent that are affordable to different earning populations. Since we also consider to explore spatial distribution about NYC apartments, location information, such as census tract, zip code, longitude and latitude, are also included in the data set. The type of variables are mostly number, basic text and date/time. There are 4,656 rows of building records in total and each row is a Housing Preservation and Development(HPD) building. The data type of features can be numeric, basic text and date.

Meanwhile, the pricing of the apartments in NYC is also a hot topic we want to explore. Unfortunately, apartment prices are not recorded in this data set. In this case, we are going to use another data set Local Law 44 Unit Income Rent which includes the number of bedrooms disaggregated by maximum allowable household income and initial legal and actual rents for each building in a Local Law 44 Housing Development Project. This data set do not include price information for all apartments, but, as a subset of all apartments, we can focus on this data set and make conclusions that can be generalized to all apartments in NYC. In this data set, building id, low/median/high initial and actual rent and total units number are recorded. Types of variables are number and plain text. There are in total 12597 rows of building records in this data set, each row is a bedroom Area Median Income(AMI) distribution.

The main issue of the second data set, Local Law 44 Unit Income Rent, is that there are a lot of missing values on the columns of initial and actual rent price. After observing the data set, we realize that all row with missing initial rents do not actual rents at the same time, and some rows only have actual rents missing Therefore, we can assume that the rows with missing values are those not rented, which can be disregarded during our research work. 

