# Data transformation

We download the two data sets mentioned in previous chapter directly from New York Open Data website in csv format so that the files can be easily read by R. After observing the data set, we notice that, in the data sets, NA are represented in different ways, using $"----"$ or $"\ "$(white space), which can not be directly identified as NA by r. So our first step is to replace these $“--”$ as NA. Recoding work is also done on some columns. In column MaxAllowableIncome” are same ranges for income such as "0%-30%" or "31%-40%" initially with levels in random orders. For future potential visualization work, it is better to reorder the levels into conceptually ascending order. Also, the numbers in the date set larger than 1000 are separated with commas. We need to remove these commas from the numbers and change their column types to numeric. Meanwhile, the date are in the format of MM-DD-YY in type of string. Data analysis and visualization work will be more convenient if we first change their type to date and use the format of YY-MM-DD.

After observing the patterns of NA values, we can confirm that the columns with around or more than 50% NAs are those columns that we do not really need for future analysis work. After removing these features, we can confirm that NAs in the rest colmns can be roughly treated as randomly generated. For the rest of the data sets, all data points with NAs are removed. In other words, we also remove the entire row with NA appearing.a

Our data are recorded in two separate files with different features: one for rent related information and the other for geography and housing related information. Combining two data sets will allow us to have more insights on our information. Therefore, we also need to merge them by their building ID.

```{r}
library(forcats)
library(ggplot2)
project = read.csv("Housing_New_York_Units_by_Building.csv", stringsAsFactors = T, na.strings=c("----", "", "NA"))
rent = read.csv("Local_Law_44_-_Unit_Income_Rent.csv", stringsAsFactors = T, na.strings=c("", "NA"))

rent$MedianActualRent = as.numeric(gsub(",", "", rent$MedianActualRent))
# remove columns that around or more than 50% values are NAs
project = subset(project, select = -c(BIN) )

# remove rows with NAs
project = na.omit(project)
rent = na.omit(rent)

# drop unused levels and reorder levels
rent$BedroomSize = droplevels(rent$BedroomSize)
rent$BedroomSize = fct_relevel(rent$BedroomSize, "STUDIO")

# merge two data sets together
data = merge(project, rent, by.x = "Building.ID", by.y = "BuildingID")

ggplot(data, aes(1: nrow(data), MedianActualRent)) +
  geom_point(alpha = 0.8)
```

From the scatterplot of the `MedianActualRent` column, we could clearly see that there is one point with value larger than 10,000 that is far from all other data points. Thus, we could take this point as an outlier and remove it from the dataset.
