# Conclusion

In this project, we make exploration on NYC Housing data. We analyzed the project activates cycle from 2014 to 2020, the relationship between bedroom size and income level, and the distribution of house rent.  We found out interesting pattern of projects started months, which are June and December and most of projects are completed in half of a year or a whole year. In the discussion of Median Actual Rent of the building, we found out that people are more likely to rent houses with more than 3 bedrooms with lower income. And the relative studio percentage is the highest among median income population, which might because of the out-of-state students and single white collar who study or work in NYC. Another interesting finding is that the preserved apartments have higher median rent than new constructed apartments. According to our discussion, it might because of the worry of indoor fitment pollution. 

But there are several limitations of our assumptions. First of all, the sample size of our data is only 10000+, which might be small to provide convincing support. Also, all of our analysis is based on housing/agent-based data. If it is possible to have data from customers’ perspective, we would better understand the underlying reasons of price fluctuation, or the project activities cycle. From learning and research perspective, if we could better understand the income level, house pricing and bedroom size relationship, we could help low-income family to look for more economical housing or start new low-rent housing construction project for them.

